### ISSUE TITLE
Add name/description to a timer

### ISSUE THREAD

**Issue by hlaueriksson** [CoreyHayward/PowerToys-Run-Timer#1]
Hi!

Nice plugin!

It would be useful to be able to add a name or description to a timer:
![image](https://github.com/CoreyHayward/PowerToys-Run-Timer/assets/1299786/e9d06200-41aa-4341-b4a7-eb32b0d5c92b)

So that one hour later I will remember why I set that timer.

**Comment by CoreyHayward** [comment]
Thanks for the suggestion! 
This has been added in [v0.2.0](https://github.com/CoreyHayward/PowerToys-Run-Timer/releases/tag/v0.2.0)
