### ISSUE TITLE
Can I change the parser options?

### ISSUE THREAD

**Issue by wisenb** [CoreyHayward/PowerToys-Run-Timer#3]
In the [TimeSpanParser](https://github.com/pengowray/TimeSpanParser) repository, this parser supports custom options.
For example,
>         // How to treat the first number, if it has no units (and no colon)
>         // e.g. Units.Minutes will mean "4" gets treated as "4 minutes"
>         public Units UncolonedDefault = Units.None;
> 
>         // How to treat the first number, if it has no units and does have a colon. 
>         // e.g. Units.Minutes will mean "4:30" gets treated as a 4m30s
>         // valid things are: Days, Hours, Minutes
>         public Units ColonedDefault = Units.Hours;

It would be perfect if user can handle parser options.

**Comment by CoreyHayward** [comment]
@wisenb Thanks a lot for the suggestion, have added both of these as configurable options in v0.3.0 which can be changed via a drop-down selection in the PT Run settings!
